- name: Configure Linux Server Users
  hosts: all
  become: true

  tasks:
    - name: Create DevOps user
      user:
        name: devopsuser
        state: present
        groups: sudo
        shell: /bin/bash

    - name: Ensure .bashrc exists
      file:
        path: /home/devopsuser/.bashrc
        state: touch
        owner: devopsuser
        group: devopsuser
